# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsC <- function(mu1, mu2, sigma1, sigma2, rho, N) {
    .Call('_StatComp22083_gibbsC', PACKAGE = 'StatComp22083', mu1, mu2, sigma1, sigma2, rho, N)
}

#' @title Compute the log-likelihood function  using Rcpp
#' @param theta ability parameter of a participant/subject/student
#' @param a discriminationparameter of an item
#' @param b difficulty parameters of an item
#' @param x subject's response to an item 
#' @examples
#' \dontrun{
#' lp<-loglikC(2,0.5,1,1)
#' }
#' @useDynLib StatComp22083
#' @export
loglikC <- function(theta, a, b, x) {
    .Call('_StatComp22083_loglikC', PACKAGE = 'StatComp22083', theta, a, b, x)
}

